# Generated by Django 2.2.4 on 2019-11-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('icon_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('icon_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('queue', models.IntegerField()),
                ('p1_duel_tier', models.IntegerField()),
                ('p1_win_status', models.CharField(max_length=6)),
                ('p1_name', models.CharField(max_length=80)),
                ('p2_duel_tier', models.IntegerField()),
                ('p2_win_status', models.CharField(max_length=6)),
                ('p2_name', models.CharField(max_length=80)),
                ('p1_active_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_active_1', to='pages.Item')),
                ('p1_active_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_active_2', to='pages.Item')),
                ('p1_god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_god', to='pages.God')),
                ('p1_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_1', to='pages.Item')),
                ('p1_item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_2', to='pages.Item')),
                ('p1_item_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_3', to='pages.Item')),
                ('p1_item_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_4', to='pages.Item')),
                ('p1_item_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_5', to='pages.Item')),
                ('p1_item_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_item_6', to='pages.Item')),
                ('p2_active_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_active_1', to='pages.Item')),
                ('p2_active_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_active_2', to='pages.Item')),
                ('p2_god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_god', to='pages.God')),
                ('p2_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_1', to='pages.Item')),
                ('p2_item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_2', to='pages.Item')),
                ('p2_item_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_3', to='pages.Item')),
                ('p2_item_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_4', to='pages.Item')),
                ('p2_item_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_5', to='pages.Item')),
                ('p2_item_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_item_6', to='pages.Item')),
            ],
        ),
    ]
