# Generated by Django 2.2.4 on 2019-11-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191124_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='datetime',
            new_name='match_datetime',
        ),
        migrations.RemoveField(
            model_name='build',
            name='datetime',
        ),
    ]
