# Generated by Django 2.2.4 on 2019-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_build_opponent_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='opponent_tier',
            field=models.IntegerField(default=0),
        ),
    ]
