# Generated by Django 2.2.4 on 2019-11-24 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191124_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='match_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='opponent_tier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_build', to='pages.Build'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_build', to='pages.Build'),
        ),
    ]
